name = "input_voltages"
description = "input voltages (in Volts x 100)"
lut_type = "uint16_t"
table_resolution_bits = 12

samples_csv = "./data/input_voltage.csv"
interpolation = "splines"                # Force a given interpolation method.
